#include "syscall.h"

t_syscall_info get_syscall_info(int id)
{
    static const t_syscall_info  syscalls_infos[] =
    {
        {"read", 3, {UINT, SIZED_STRING, ULONG}, 1, LONG},
        {"write", 3, {UINT, SIZED_STRING, ULONG}, -1, LONG},
        {"open", 3, {FILENAME, INT, INT}, -1, LONG},
        {"close", 1, {UINT}, -1, LONG},
        {"stat", 2, {FILENAME, ADDR}, 1, LONG},
        {"fstat", 2, {UINT, ADDR}, 1, LONG},
        {"lstat", 2, {FILENAME, ADDR}, 1, LONG},
        {"poll", 3, {ADDR, UINT, LONG}, -1, LONG},
        {"lseek", 3, {UINT, ADDR, UINT}, -1, LONG},
        {"mmap", 6, {ULONG, ULONG, ULONG, ULONG, ULONG, ULONG}, -1, LONG},
        {"mprotect", 3, {ULONG, ULONG, ULONG}, -1, LONG},
        {"munmap", 2, {ULONG, ULONG}, -1, LONG},
        {"brk", 1, {ULONG}, -1, LONG},
        {"rt_sigaction", 4, {INT, ADDR, ADDR, ULONG}, -1, LONG},
        {"rt_sigprocmask", 4, {INT, ADDR, ADDR, ULONG}, -1, LONG},
        {"rt_sigreturn", 1, {ULONG}, -1, LONG},
        {"ioctl", 3, {UINT, UINT, ULONG}, -1, LONG},
        {"pread64", 4, {ULONG, STRING, ULONG, ADDR}, 1, LONG},
        {"pwrite64", 4, {UINT, STRING, ULONG, ADDR}, 1, LONG},
        {"readv", 3, {ULONG, ADDR, ULONG}, -1, LONG},
        {"writev", 3, {ULONG, ADDR, ULONG}, -1, LONG},
        {"access", 2, {FILENAME, INT}, -1, LONG},
        {"pipe", 1, {INT}, -1, LONG},
        {"select", 5, {INT, ADDR, ADDR, ADDR, ADDR}, -1, LONG},
        {"sched_yield", 0, {}, -1, LONG},
        {"mremap", 5, {ULONG, ULONG, ULONG, ULONG, ULONG}, -1, LONG},
        {"msync", 3, {ULONG, ULONG, INT}, -1, LONG},
        {"mincore", 3, {ULONG, ULONG, STRING}, -1, LONG},
        {"madvise", 3, {ULONG, ULONG, INT}, -1, LONG},
        {"shmget", 3, {ADDR, ULONG, INT}, -1, LONG},
        {"shmat", 3, {INT, STRING, INT}, -1, LONG},
        {"shmctl", 3, {INT, INT, ADDR}, 2, LONG},
        {"dup", 1, {UINT}, -1, LONG},
        {"dup2", 2, {UINT, UINT}, -1, LONG},
        {"pause", 0, {}, -1, LONG},
        {"nanosleep", 2, {ADDR, ADDR}, -1, LONG},
        {"getitimer", 2, {INT, ADDR}, -1, LONG},
        {"alarm", 1, {UINT}, -1, LONG},
        {"setitimer", 3, {INT, ADDR, ADDR}, -1, LONG},
        {"getpid", 0, {}, -1, LONG},
        {"sendfile", 4, {INT, INT, ADDR, ULONG}, -1, LONG},
        {"socket", 3, {INT, INT, INT}, -1, LONG},
        {"connect", 3, {INT, ADDR, INT}, -1, LONG},
        {"accept", 3, {INT, ADDR, INT}, -1, LONG},
        {"sendto", 6, {INT, ADDR, ULONG, ADDR, ADDR, INT}, 1, LONG},
        {"recvfrom", 6, {INT, ADDR, ULONG, ADDR, ADDR, INT}, 1, LONG},
        {"sendmsg", 3, {INT, ADDR, ADDR}, -1, LONG},
        {"recvmsg", 3, {INT, ADDR, UINT}, -1, LONG},
        {"shutdown", 2, {INT, INT}, -1, LONG},
        {"bind", 3, {INT, ADDR, INT}, -1, LONG},
        {"listen", 2, {INT, INT}, -1, LONG},
        {"getsockname", 3, {INT, ADDR, INT}, -1, LONG},
        {"getpeername", 3, {INT, ADDR, INT}, -1, LONG},
        {"socketpair", 4, {INT, INT, INT, INT}, -1, LONG},
        {"setsockopt", 5, {INT, INT, INT, STRING, INT}, -1, LONG},
        {"getsockopt", 5, {INT, INT, INT, STRING, INT}, -1, LONG},
        {"clone", 5, {ULONG, ULONG, ADDR, ADDR, UINT}, -1, LONG},
        {"fork", 0, {}, -1, LONG},
        {"vfork", 0, {}, -1, LONG},
        {"execve", 3, {FILENAME, STRING_ARRAY, STRING_ARRAY}, -1, LONG},
        {"exit", 1, {INT}, -1, LONG},
        {"wait4", 4, {ADDR, INT, INT, ADDR}, -1, LONG},
        {"kill", 2, {ADDR, INT}, -1, LONG},
        {"uname", 1, {ADDR}, -1, LONG},
        {"semget", 3, {ADDR, INT, INT}, -1, LONG},
        {"semop", 3, {INT, ADDR, ADDR}, 1, LONG},
        {"semctl", 4, {INT, INT, INT, ADDR}, -1, LONG},
        {"shmdt", 1, {STRING}, -1, LONG},
        {"msgget", 2, {ADDR, INT}, -1, LONG},
        {"msgsnd", 4, {INT, ADDR, ULONG, INT}, 1, LONG},
        {"msgrcv", 5, {INT, ADDR, ULONG, LONG, INT}, 1, LONG},
        {"msgctl", 3, {INT, INT, ADDR}, 2, LONG},
        {"fcntl", 3, {UINT, UINT, ULONG}, -1, LONG},
        {"flock", 2, {UINT, UINT}, -1, LONG},
        {"fsync", 1, {UINT}, -1, LONG},
        {"fdatasync", 1, {UINT}, -1, LONG},
        {"truncate", 2, {STRING, LONG}, -1, LONG},
        {"ftruncate", 2, {UINT, ULONG}, -1, LONG},
        {"getdents", 3, {UINT, ADDR, UINT}, -1, LONG},
        {"getcwd", 2, {STRING, ULONG}, 0, LONG},
        {"chdir", 1, {FILENAME}, -1, LONG},
        {"fchdir", 1, {UINT}, -1, LONG},
        {"rename", 2, {STRING, STRING}, -1, LONG},
        {"mkdir", 2, {STRING, INT}, -1, LONG},
        {"rmdir", 1, {STRING}, -1, LONG},
        {"creat", 2, {STRING, INT}, -1, LONG},
        {"link", 2, {STRING, STRING}, -1, LONG},
        {"unlink", 1, {STRING}, -1, LONG},
        {"symlink", 2, {STRING, STRING}, -1, LONG},
        {"readlink", 3, {STRING, STRING, INT}, 2, LONG},
        {"chmod", 2, {FILENAME, ADDR}, -1, LONG},
        {"fchmod", 2, {UINT, ADDR}, -1, LONG},
        {"chown", 3, {FILENAME, ADDR, ADDR}, -1, LONG},
        {"fchown", 3, {UINT, ADDR, ADDR}, -1, LONG},
        {"lchown", 3, {FILENAME, ADDR, ADDR}, -1, LONG},
        {"umask", 1, {INT}, -1, LONG},
        {"gettimeofday", 2, {ADDR, ADDR}, -1, LONG},
        {"getrlimit", 2, {UINT, ADDR}, -1, LONG},
        {"getrusage", 2, {INT, ADDR}, -1, LONG},
        {"sysinfo", 1, {ADDR}, -1, LONG},
        {"times", 1, {ADDR}, -1, LONG},
        {"ptrace", 4, {LONG, LONG, ULONG, ULONG}, -1, LONG},
        {"getuid", 0, {}, -1, LONG},
        {"syslog", 3, {INT, STRING, INT}, 1, LONG},
        {"getgid", 0, {}, -1, LONG},
        {"setuid", 1, {ADDR}, -1, LONG},
        {"setgid", 1, {ADDR}, -1, LONG},
        {"geteuid", 0, {}, -1, LONG},
        {"getegid", 0, {}, -1, LONG},
        {"setpgid", 2, {ADDR, ADDR}, -1, LONG},
        {"getppid", 0, {}, -1, LONG},
        {"getpgrp", 0, {}, -1, LONG},
        {"setsid", 0, {}, -1, LONG},
        {"setreuid", 2, {ADDR, ADDR}, -1, LONG},
        {"setregid", 2, {ADDR, ADDR}, -1, LONG},
        {"getgroups", 2, {INT, ADDR}, -1, LONG},
        {"setgroups", 2, {INT, ADDR}, -1, LONG},
        {"setresuid", 3, {ADDR, ADDR, ADDR}, -1, LONG},
        {"getresuid", 3, {ADDR, ADDR, ADDR}, -1, LONG},
        {"setresgid", 3, {ADDR, ADDR, ADDR}, -1, LONG},
        {"getresgid", 3, {ADDR, ADDR, ADDR}, -1, LONG},
        {"getpgid", 1, {ADDR}, -1, LONG},
        {"setfsuid", 1, {ADDR}, -1, LONG},
        {"setfsgid", 1, {ADDR}, -1, LONG},
        {"getsid", 1, {ADDR}, -1, LONG},
        {"capget", 2, {ADDR, ADDR}, -1, LONG},
        {"capset", 2, {ADDR, ADDR}, -1, LONG},
        {"rt_sigpending", 2, {ADDR, ULONG}, -1, LONG},
        {"rt_sigtimedwait", 4, {ADDR, ADDR, ADDR, ULONG}, -1, LONG},
        {"rt_sigqueueinfo", 3, {ADDR, INT, ADDR}, -1, LONG},
        {"rt_sigsuspend", 2, {ADDR, ULONG}, -1, LONG},
        {"sigaltstack", 2, {ADDR, ADDR}, -1, LONG},
        {"utime", 2, {FILENAME, ADDR}, 1, LONG},
        {"mknod", 3, {FILENAME, ADDR, ADDR}, -1, LONG},
        {"uselib", 1, {ADDR}, -1, LONG},
        {"personality", 1, {UINT}, -1, LONG},
        {"ustat", 2, {ADDR, ADDR}, 1, LONG},
        {"statfs", 2, {STRING, ADDR}, 1, LONG},
        {"fstatfs", 2, {UINT, ADDR}, 1, LONG},
        {"sysfs", 3, {INT, ULONG, ULONG}, -1, LONG},
        {"getpriority", 2, {INT, INT}, -1, LONG},
        {"setpriority", 3, {INT, INT, INT}, -1, LONG},
        {"sched_setparam", 2, {ADDR, ADDR}, -1, LONG},
        {"sched_getparam", 2, {ADDR, ADDR}, -1, LONG},
        {"sched_setscheduler", 3, {ADDR, INT, ADDR}, -1, LONG},
        {"sched_getscheduler", 1, {ADDR}, -1, LONG},
        {"sched_get_priority_max", 1, {INT}, -1, LONG},
        {"sched_get_priority_min", 1, {INT}, -1, LONG},
        {"sched_rr_get_interval", 2, {ADDR, INT}, -1, LONG},
        {"mlock", 2, {ULONG, ULONG}, -1, LONG},
        {"munlock", 2, {ULONG, ULONG}, -1, LONG},
        {"mlockall", 1, {INT}, -1, LONG},
        {"munlockall", 0, {}, -1, LONG},
        {"vhangup", 0, {}, -1, LONG},
        {"modify_ldt", 3, {INT, ADDR, ULONG}, -1, LONG},
        {"pivot_root", 2, {STRING, STRING}, -1, LONG},
        {"_sysctl", 1, {ADDR}, -1, LONG},
        {"prctl", 5, {INT, ULONG, ULONG, ULONG, ULONG}, -1, LONG},
        {"arch_prctl", 3, {ADDR, INT, ULONG}, -1, LONG},
        {"adjtimex", 1, {ADDR}, -1, LONG},
        {"setrlimit", 2, {UINT, ADDR}, -1, LONG},
        {"chroot", 1, {FILENAME}, -1, LONG},
        {"sync", 0, {}, -1, LONG},
        {"acct", 1, {STRING}, -1, LONG},
        {"settimeofday", 2, {ADDR, ADDR}, -1, LONG},
        {"mount", 5, {STRING, STRING, STRING, ULONG, ADDR}, -1, LONG},
        {"umount2", 2, {STRING, INT}, -1, LONG},
        {"swapon", 2, {STRING, INT}, -1, LONG},
        {"swapoff", 1, {STRING}, -1, LONG},
        {"reboot", 4, {INT, INT, UINT, ADDR}, -1, LONG},
        {"sethostname", 2, {STRING, INT}, -1, LONG},
        {"setdomainname", 2, {STRING, INT}, -1, LONG},
        {"iopl", 2, {UINT, ADDR}, -1, LONG},
        {"ioperm", 3, {ULONG, ULONG, INT}, -1, LONG},
        {"create_module", 1, {ADDR}, -1, LONG},
        {"init_module", 3, {ADDR, ULONG, STRING}, -1, LONG},
        {"delete_module", 2, {ADDR, UINT}, -1, LONG},
        {"get_kernel_syms", 1, {ADDR}, -1, LONG},
        {"query_module", 1, {ADDR}, -1, LONG},
        {"quotactl", 4, {UINT, STRING, ADDR, ADDR}, -1, LONG},
        {"nfsservctl", 1, {ADDR}, -1, LONG},
        {"getpmsg", 1, {ADDR}, -1, LONG},
        {"putpmsg", 1, {ADDR}, -1, LONG},
        {"afs_syscall", 1, {ADDR}, -1, LONG},
        {"tuxcall", 1, {ADDR}, -1, LONG},
        {"security", 1, {ADDR}, -1, LONG},
        {"gettid", 0, {}, -1, LONG},
        {"readahead", 3, {INT, ADDR, ULONG}, -1, LONG},
        {"setxattr", 5, {STRING, STRING, ADDR, ULONG, INT}, -1, LONG},
        {"lsetxattr", 5, {STRING, STRING, ADDR, ULONG, INT}, -1, LONG},
        {"fsetxattr", 5, {INT, STRING, ADDR, ULONG, INT}, -1, LONG},
        {"getxattr", 4, {STRING, STRING, ADDR, ULONG}, -1, LONG},
        {"lgetxattr", 4, {STRING, STRING, ADDR, ULONG}, -1, LONG},
        {"fgetxattr", 4, {INT, ADDR, ADDR, ULONG}, -1, LONG},
        {"listxattr", 3, {STRING, STRING, ULONG}, -1, LONG},
        {"llistxattr", 3, {STRING, STRING, ULONG}, -1, LONG},
        {"flistxattr", 3, {INT, STRING, ULONG}, -1, LONG},
        {"removexattr", 2, {STRING, STRING}, -1, LONG},
        {"lremovexattr", 2, {STRING, STRING}, -1, LONG},
        {"fremovexattr", 2, {INT, STRING}, -1, LONG},
        {"tkill", 2, {ADDR, ADDR}, -1, LONG},
        {"time", 1, {ADDR}, -1, LONG},
        {"futex", 6, {ADDR, INT, ADDR, ADDR, ADDR, ADDR}, -1, LONG},
        {"sched_setaffinity", 3, {ADDR, UINT, ULONG}, -1, LONG},
        {"sched_getaffinity", 3, {ADDR, UINT, ULONG}, -1, LONG},
        {"set_thread_area", 1, {ADDR}, -1, LONG},
        {"io_setup", 2, {ADDR, ADDR}, -1, LONG},
        {"io_destroy", 1, {ADDR}, -1, LONG},
        {"io_getevents", 4, {ADDR, LONG, LONG, ADDR}, -1, LONG},
        {"io_submit", 3, {ADDR, LONG, ADDR}, -1, LONG},
        {"io_cancel", 3, {ADDR, ADDR, ADDR}, -1, LONG},
        {"get_thread_area", 1, {ADDR}, -1, LONG},
        {"lookup_dcookie", 3, {ADDR, LONG, LONG}, 1, LONG},
        {"epoll_create", 1, {INT}, -1, LONG},
        {"epoll_ctl_old", 1, {ADDR}, -1, LONG},
        {"epoll_wait_old", 1, {ADDR}, -1, LONG},
        {"remap_file_pages", 5, {ULONG, ULONG, ULONG, ULONG, ULONG}, -1, LONG},
        {"getdents64", 3, {UINT, ADDR, UINT}, -1, LONG},
        {"set_tid_address", 1, {INT}, -1, LONG},
        {"restart_syscall", 0, {}, -1, LONG},
        {"semtimedop", 4, {INT, ADDR, ADDR, ADDR}, 1, LONG},
        {"fadvise64", 4, {INT, ADDR, ULONG, INT}, -1, LONG},
        {"timer_create", 3, {ADDR, ADDR, ADDR}, -1, LONG},
        {"timer_settime", 4, {ADDR, INT, ADDR, ADDR}, -1, LONG},
        {"timer_gettime", 2, {ADDR, ADDR}, -1, LONG},
        {"timer_getoverrun", 1, {ADDR}, -1, LONG},
        {"timer_delete", 1, {ADDR}, -1, LONG},
        {"clock_settime", 2, {ADDR, ADDR}, -1, LONG},
        {"clock_gettime", 2, {ADDR, ADDR}, -1, LONG},
        {"clock_getres", 2, {ADDR, ADDR}, -1, LONG},
        {"clock_nanosleep", 4, {ADDR, INT, ADDR, ADDR}, -1, LONG},
        {"exit_group", 1, {INT}, -1, LONG},
        {"epoll_wait", 4, {INT, ADDR, INT, INT}, -1, LONG},
        {"epoll_ctl", 4, {INT, INT, INT, ADDR}, -1, LONG},
        {"tgkill", 3, {ADDR, ADDR, INT}, -1, LONG},
        {"utimes", 2, {FILENAME, ADDR}, -1, LONG},
        {"vserver", 1, {ADDR}, -1, LONG},
        {"mbind", 6, {ULONG, ULONG, ULONG, ULONG, ULONG, ADDR}, -1, LONG},
        {"set_mempolicy", 3, {INT, ULONG, ULONG}, -1, LONG},
        {"get_mempolicy", 5, {INT, ULONG, ULONG, ULONG, ULONG}, -1, LONG},
        {"mq_open", 4, {STRING, INT, ADDR, ADDR}, -1, LONG},
        {"mq_unlink", 1, {STRING}, -1, LONG},
        {"mq_timedsend", 5, {ADDR, STRING, ULONG, UINT, ADDR}, -1, LONG},
        {"mq_timedreceive", 5, {ADDR, STRING, ULONG, UINT, ADDR}, -1, LONG},
        {"mq_notify", 2, {ADDR, ADDR}, -1, LONG},
        {"mq_getsetattr", 3, {ADDR, ADDR, ADDR}, -1, LONG},
        {"kexec_load", 4, {ULONG, ULONG, ADDR, ULONG}, -1, LONG},
        {"waitid", 5, {INT, ADDR, ADDR, INT, ADDR}, -1, LONG},
        {"add_key", 4, {STRING, STRING, ADDR, ULONG}, -1, LONG},
        {"request_key", 4, {STRING, STRING, STRING, ADDR}, -1, LONG},
        {"keyctl", 5, {INT, ULONG, ULONG, ULONG, ULONG}, -1, LONG},
        {"ioprio_set", 3, {INT, INT, INT}, -1, LONG},
        {"ioprio_get", 2, {INT, INT}, -1, LONG},
        {"inotify_init", 0, {}, -1, LONG},
        {"inotify_add_watch", 3, {INT, STRING, ADDR}, -1, LONG},
        {"inotify_rm_watch", 2, {INT, ADDR}, -1, LONG},
        {"migrate_pages", 4, {ADDR, ULONG, ULONG, ULONG}, -1, LONG},
        {"openat", 4, {INT, FILENAME, INT, INT}, -1, LONG},
        {"mkdirat", 3, {INT, STRING, INT}, -1, LONG},
        {"mknodat", 4, {INT, FILENAME, INT, ADDR}, -1, LONG},
        {"fchownat", 5, {INT, FILENAME, ADDR, ADDR, INT}, -1, LONG},
        {"futimesat", 3, {INT, FILENAME, ADDR}, -1, LONG},
        {"newfstatat", 4, {INT, FILENAME, ADDR, INT}, 2, LONG},
        {"unlinkat", 3, {INT, STRING, INT}, -1, LONG},
        {"renameat", 4, {INT, STRING, INT, STRING}, -1, LONG},
        {"linkat", 5, {INT, STRING, INT, STRING, INT}, -1, LONG},
        {"symlinkat", 3, {STRING, INT, STRING}, -1, LONG},
        {"readlinkat", 4, {INT, FILENAME, STRING, INT}, 2, LONG},
        {"fchmodat", 3, {INT, FILENAME, ADDR}, -1, LONG},
        {"faccessat", 3, {INT, FILENAME, INT}, -1, LONG},
        {"pselect6", 6, {INT, ADDR, ADDR, ADDR, ADDR, ADDR}, -1, LONG},
        {"ppoll", 5, {ADDR, UINT, ADDR, ADDR, ULONG}, -1, LONG},
        {"unshare", 1, {ULONG}, -1, LONG},
        {"set_robust_list", 2, {ADDR, ULONG}, -1, LONG},
        {"get_robust_list", 3, {INT, ADDR, ULONG}, -1, LONG},
        {"splice", 6, {INT, ADDR, INT, ADDR, ULONG, UINT}, -1, LONG},
        {"tee", 4, {INT, INT, ULONG, UINT}, -1, LONG},
        {"sync_file_range", 4, {LONG, ADDR, ADDR, LONG}, -1, LONG},
        {"vmsplice", 4, {INT, ADDR, ULONG, UINT}, -1, LONG},
        {"move_pages", 6, {ADDR, ULONG, ADDR, INT, INT, INT}, -1, LONG},
        {"utimensat", 4, {INT, FILENAME, ADDR, INT}, -1, LONG},
        {"epoll_pwait", 6, {INT, ADDR, INT, INT, ADDR, ULONG}, -1, LONG},
        {"signalfd", 3, {INT, ADDR, ULONG}, -1, LONG},
        {"timerfd_create", 2, {INT, INT}, -1, LONG},
        {"eventfd", 1, {UINT}, -1, LONG},
        {"fallocate", 4, {LONG, LONG, ADDR, ADDR}, -1, LONG},
        {"timerfd_settime", 4, {INT, INT, ADDR, ADDR}, -1, LONG},
        {"timerfd_gettime", 2, {INT, ADDR}, -1, LONG},
        {"accept4", 4, {INT, ADDR, INT, INT}, -1, LONG},
        {"signalfd4", 4, {INT, ADDR, ULONG, INT}, -1, LONG},
        {"eventfd2", 2, {UINT, INT}, -1, LONG},
        {"epoll_create1", 1, {INT}, -1, LONG},
        {"dup3", 3, {UINT, UINT, INT}, -1, LONG},
        {"pipe2", 2, {INT, INT}, -1, LONG},
        {"inotify_init1", 1, {INT}, -1, LONG},
        {"preadv", 5, {ULONG, ADDR, ULONG, ULONG, ULONG}, -1, LONG},
        {"pwritev", 5, {ULONG, ADDR, ULONG, ULONG, ULONG}, -1, LONG},
        {"rt_tgsigqueueinfo", 4, {ADDR, ADDR, INT, ADDR}, -1, LONG},
        {"perf_event_open", 5, {ADDR, ADDR, INT, INT, ULONG}, -1, LONG},
        {"recvmmsg", 5, {INT, ADDR, UINT, UINT, ADDR}, -1, LONG},
        {"fanotify_init", 2, {UINT, UINT}, -1, LONG},
        {"fanotify_mark", 5, {LONG, LONG, ADDR, LONG, LONG}, -1, LONG},
        {"prlimit64", 4, {ADDR, UINT, ADDR, ADDR}, -1, LONG},
        {"name_to_handle_at", 5, {INT, STRING, ADDR, INT, INT}, -1, LONG},
        {"open_by_handle_at", 5, {INT, STRING, ADDR, INT, INT}, -1, LONG},
        {"clock_adjtime", 2, {ADDR, ADDR}, -1, LONG},
        {"syncfs", 1, {INT}, -1, LONG},
        {"sendmmsg", 4, {INT, ADDR, UINT, UINT}, -1, LONG},
        {"setns", 2, {INT, INT}, -1, LONG},
        {"getcpu", 3, {ADDR, ADDR, ADDR}, -1, LONG},
        {"process_vm_readv", 6, {ADDR, ADDR, ULONG, ADDR, ULONG, ULONG}, -1, LONG},
        {"process_vm_writev", 6, {ADDR, ADDR, ULONG, ADDR, ULONG, ULONG}, -1, LONG},
        {"kcmp", 5, {ADDR, ADDR, INT, ULONG, ULONG}, -1, LONG},
        {"finit_module", 3, {INT, ADDR, INT}, -1, LONG},
        {"sched_setattr", 3, {ADDR, ADDR, UINT}, -1, LONG},
        {"sched_getattr", 4, {ADDR, ADDR, UINT, UINT}, -1, LONG},
        {"renameat2", 5, {INT, ADDR, INT, ADDR, UINT}, -1, LONG},
        {"seccomp", 3, {UINT, UINT, ADDR}, -1, LONG},
        {"getrandom", 3, {ADDR, ULONG, UINT}, 0, LONG},
        {"memfd_create", 2, {ADDR, INT}, -1, LONG},
        {"kexec_file_load", 5, {INT, INT, ULONG, ADDR, ULONG}, -1, LONG},
        {"bpf", 3, {INT, ADDR, UINT}, -1, LONG},
        {"_execveat", 5, {INT, FILENAME, ADDR, ADDR, INT}, -1, LONG},
        {"faultfd", 1, {INT}, -1, LONG},
        {"arrier", 2, {INT, INT}, -1, LONG},
        {"k2", 3, {ULONG, ULONG, INT}, -1, LONG},
        {"_file_range", 6, {INT, ADDR, INT, ADDR, ULONG, UINT}, -1, LONG},
        {"dv2", 6, {ULONG, ADDR, ULONG, ULONG, ULONG, INT}, -1, LONG},
        {"tev2", 6, {ULONG, ADDR, ULONG, ULONG, ULONG, INT}, -1, LONG},
        {"_mprotect", 0, {}, -1, LONG},
        {"_alloc", 0, {}, -1, LONG},
        {"_free", 0, {}, -1, LONG},
        {"x", 0, {}, -1, LONG},
        {"getevents", 0, {}, -1, LONG},
        {"", 0, {}, -1, LONG}
    };
    return syscalls_infos[id];
}

int get_arg_offset(int arg_index)
{
    static const int arg_regs[] = {RDI, RSI, RDX, R10, R8, R9};
    return arg_regs[arg_index];
}
